openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SITEPROJECTOR/doc-configurator/1.0.0
info:
  title: Doc Configurator API
  version: "1.0.0"
tags:
  - name: Documents
    description: "Documents created from Document Templates"
  - name: DocTemplates
    description: "Document Templates for creating documents"